#testing #get_speech(text = "") length limits

a <- "Hey Tony biology fans, my name is Matt Hershey. still with us. Awesome. Welcome to class three. In the last class, we talked about the package supplier, a very verbs that apply our uses and how to manipulate our data and start getting insight into it. Today's class will be focusing on data visualization, while they're in the package GG plot will learn about the grammar of graphics, and how to make simple but effective visualizations. And individualized individualize. Today is a lecture by Dr. Holly mill, she will be telling us about GG plot. So GG plot is one 100"
b <- "of the packages within the tidy verse sort of ecosystem, that is, arguably the reason that people use the tidy verse. So the ability to take data and turn it into a visualization and a couple of lines of code is an incredibly powerful thing. And that's what we're gonna be going over today. And I guess without further ado. Okay, so for those of you who have any experience with GG plot, this is going to be a very basic introduction. So bear with me. So as Matt said, GG plot is this amazingly powerful graphing package within the 100"
c <- "tidy verse. And just to give you an idea of what it can do, you can make graphics like this, where your data transforms, you can even make these sorts of infographics you often see in the news. And this is specifically how the BBC makes its infographics. They said, the reason they use GG plot is because you have a huge number of graphics available to you, it saves time and effort because you can remake the same things, you can copy and paste, like we've said before. And you can update it regularly, and it's highly reproducible. They, 100"
d <- "they use GG plot so much they've even made their own package called BB plot, which covers all the BBC themes. So if you really like BBC themes, you can download that. Um, so graphing is really important because simple graphs, as this quote says, The simple graph has brought more information to the data analysts mind than any other device. That's because, as humans, we really react to a visual representation of data, much more than we do to a table or a list. So we can really get our point across easily and quickly using graphics. So to 100"
e <- "start off, I don't know if all of you have the GG plot lecture RMD open, this is going to be kind of a code along. So if you don't have that open, go ahead and open it. And for the first exercise, we're going to use the chromosome data set that we've used before. So in your code along RMD, you'll have you need to load the packages. But you also are though the libraries and you also need to load the chromosome data set as well as another data set that's included in there. So as I said 100"
f <- ", we'll start out with this chromosome data set. And here again, is what our data set looks like. As a reminder, we have face pairs variations, protein coding genes, information like that. So I want to start out by asking a simple question. What relationship do we expect to see between chromosome size and the number of protein coding genes? You can actually answer this. Anyone? It's not difficult. It's not a trick question. Okay, so you expect to see more protein coding genes for the longer chromosomes? Yes. Okay. So, for our first exercise, you should have this 100"
g <- "chunk of code already written in your in your file, and I just want you to run it just to see what it looks like. So this should look similar to something you made on day one. Okay, so if you ran that chunk of code successfully, you should get a plot that looks like this, right? So a very simple plot where you can see we've mapped the length in millimeters on the x axis versus protein coding genes. And we can see a trend as we might have expected that the longer the chromosome, the more protein coding 100 "
h <- "genes there are, that's not necessary, necessarily a perfect trend, but It sticks with it. So what do we do with this piece of code. So what we did is we took data. And here's a nice little definition, but I saw format, where a statistical graphic is a mapping of data variables to an aesthetic attributes of a geometric object. So here we've taken the data chromosome, and we've mapped it to the geometric object, which is a scatterplot. And in this example, we've mapped the length in millimeters, and the protein coding genes. So this code is made 100"
i <- "up of two primary tracks. The first is the chunk in which we initialize our plot using the GG plot function. So here is where you're going to assign your data. After that, there's a plus sign. So does anybody have any idea what the plus sign is, and how it might relate to something you've seen before? Yes, it is GG plots version of a pipe. So you want to add the plus sign, because then you will get the end, then you're going to add this next layer. So the second part of this code is the layer, "
j <- "which is the geometric function. So in this case, it's g on point. So GM point is a scatterplot. And there are lots of different types of genes which we'll go over in a moment. And in that layer, you map your aesthetics. So in this point, its x&y. So one stylistic rule that we've kind of talked a little bit about is like pipes, you probably want to keep your plus sign at the end of your line. This is for, you know, just stylistic reasons, you can put it at the beginning of your GM point. But it most code you will see we'll put it at the end of your line."

long_text <- str_c(a, b, c, d, e)
get_speech(text = a)
get_speech(text = long_text)

#per API
#string <= 1000 characters

#makes a list of text
tts_split_text(long_text, limit = 1000)
